spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oponex
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
